server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/game
    username:
      root
    password:
      123456

jpa:
  properties:
    hibernate:
      dialect:
        org.hibernate.dialect.MySQLDialect